- MyFirstLab
Let's get serious about getting the labs going!
> MyFirstLab

- proposal-template.md
> Add proposal template for new labs.

- labs/README.MD
- labs/archived/README.md
> Add the directory to hold new lab proposals and archived lab proposals.

- README.md
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
> Add basic process to propose a new lab.

- README.md
> Add a link to the repository that should be forked.

- README.md
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
> Added section on bringing an existing repo

- README.md
> Redo change to include link to the repository.

- labs/PrivateDataObjects.md
- labs/private-data-objects.md
Signed-off-by: Mic Bowman <mic.bowman@intel.com>
> Hyperledger Labs proposal for Private Data Objects.

- proposal-template.md
> Added a note that a sponsor is required for a lab proposal

- labs/crypto-lib.md
Adding crypto-lib proposal for labs
> crypto-lib Proposal

- labs/fabric-chrome-extension
Signed-off-by: Daniel McSheehy <dsm140130@utdallas.edu>
> Hyperledger Fabric Chrome Extension Lab Proposal

- labs/fabric-chrome-extension.md
Signed-off-by: Daniel McSheehy <dsm140130@utdallas.edu>
> Updating sponsor information

- labs/hyperledger-docs-cn.md
Signed-off-by: Jiang Lu lujjiang@cn.ibm.com
> Fabric documentation translation to Chinese

- labs/fabric-secure-chaincode.md
Signed-off-by: Marcus Brandenburger <bur@zurich.ibm.com>
> Propose secure chaincode execution for Fabric

- labs/fabric-vms-provision.md
Ansible based example, for provisioning Hyperledger Fabric native binaries across multiple vms.
> fabric vms provision

- labs/umbra.md
This is the labs proposal for the Umbra project.
Signed-off-by: Dave Huseby <dhuseby@linuxfoundation.org>
> adding umbra proposal

- labs/fabric-multi-channel-network-samples.md
Fabric Multi Channel Network Samples
This lab provides samples for multi channel network using Hyperledger Fabric.
* bin : The built binaries, after scripts/bootstrap.sh, which needed to run for the first time.
* chaincode : Chaincodes for the samples.
* multi-channel-network : The first sample based on 'BYFN' in 'fabric-samples' repo.
* fabric-ca : The second sample based on 'fabric-ca' in 'fabric-samples' repo.
This lab is based on [Build Your First Network](https://github.com/hyperledger/fabric-samples).
After the [tutorial](https://hyperledger-fabric.readthedocs.io/en/latest/build_network.html), a Fabric beginner may want to find out multi channel network samples, and these are the samples.
Currently, There are two multi-channel-network samples from 'byfn' and 'fabric-ca' both are …
> proposal for fabric-multi-channel-network-samples

- labs/cordentity.md
Luxoft would like to bring Cordentity to Hyperledger. 
Signed-off-by: Jeremiah C. Foster <jfoster@luxoft.com>
> Added Cordentity proposal

- README.md
Signed-off-by: Jeremiah C. Foster <jeremiah@jeremiahfoster.com>
> Update README.md with link to DCO

- labs/private-transaction-families.md
Signed-off-by: Shefy Gur-Ary <shefy.gurary@intel.com>
> Private transaction families

- labs/private-transaction-families.md
> Remove word project

- labs/byzantine-config.md
Signed-off-by: dpitt <dpitt@keyholesoftware.com>
> Hyperledger labs proposal submission

- labs/fabric-lightweight-client.md
The project aims to enable lightweight (IoT) devices to act as a Lightweight (Hyperledger Fabric) Client and communicate through a Proxy directly with the Hyperledger Fabric network.
> Hyperledger Fabric Lightweight Client proposal

- labs/sawtooth-poet2.md
Create a new repository for the Hyperledger Sawtooth PoET 2.
Proposing a new experimental protocol sawtooth-poet2.
Signed-off-by: S m, Aruna <aruna.s.m@intel.com>
> Propose sawtooth-poet2

- labs/blockchain-analyzer.md
Signed-off-by: Balazs Prehoda <prehoda.balazs@gmail.com>
> Proposal for Blockchain Analyzer

- README.md
Lab proposal submitters consistently stumble over the lack of sign-off. This note will hopefully
provide them with proper guidance.
Signed-off-by: Arnaud J Le Hors <lehors@us.ibm.com>
> Added note about having proper sign-off on commit

- labs/patient-consent.md
Use Case Patient Data in Clinical Trials Automation with focus of Patient Consent
We want to develop the integration of stakeholders in one platform, starting incrementally 
with small fragments of the eco system; e.g. Clinical Studies; electronic informed consent 
on a small enterprise blockchain/closed ledger system, healthcare chain ensuring secure 
flows of sensitive data on the cloud with rules and governance on the Hyperledger Frameworks. 
We aim to provide value to two main stakeholder groups: Pharma companies/Medtech with CROs and Patients. 
Use case realizations with two frameworks, Hyperledger Fabric and Sawtooth
> Add Patient Consent Lab

- gardener.md
Signed-off-by: Krzysztof Spisak-Spisacki <krzysztof.spisak.spisacki@espeo.eu>
> Gardener proposal

- labs/fabric-block-archiving.md
The project aims to reduce the total amount of storage space required for an organisation to operate a Hyperledger Fabric network by archiving block data into a repository.
> Proposal for Hyperledger Fabric Block Archiving

- labs/ethercluster.md
Signed-off-by: Yaz Khoury yaz@etccooperative.org
Adds the Ethercluster proposal to Hyperledger Labs
> Yaz.ethercluster proposal

- labs/blockchain-verifier.md
A tool to check and verify the integrity of ledgers and the correctness of smart contracts
Signed-off-by: Taku Shimosawa <taku.shimosawa@hal.hitachi.com>
> Blockchain Verifier

- labs/chaincode-analyzer.md
Short Description
A static tool to check and detect potentially risky codes in smart contracts (a.k.a, chaincodes).
> Proposal for Chaincode Analyzer

- labs/fabric-chaincode-haskell.md
`fabric-chaincode-haskell` is a Haskell shim for Hyperledger Fabric to allow the authoring of smart contracts in Haskell.
As chaincode often contains business and security critical code, it is important that the code is correct. Implications for contracts containing bugs and exploits can lead to attacks like the DAO and Parity attacks on the Ethereum blockchain, which can have significant economic impacts. Functionally pure and strongly typed languages like Haskell provide a much greater degree of confidence in correctness. `fabric-chaincode-haskell` allows the authorship of chaincode that gives a higher confidence of correctness.
Allowing chaincode to be authored in Haskell also opens up the world of blockchain to the large and enthusiastic community of Haskell developers.
> fabric-chaincode-haskell

- labs/fabric-docs-ml.md
…abric
Signed-off-by: Anthony O'Dowd <a_o-dowd@uk.ibm.com>
A project to translate the Fabric documentation into Malayalam.
> fabric-docs-ml

- labs/fabric-healthcare-payer-prescription
- labs/modern-pharmacy-management.md
Proposal for creating the lab for Pharmacy Management use case Payer Sub Group.
Signed-off-by: Raveesh Dewan <dewanraveesh@gmail.com>
> Proposal for creating the lab for Pharmacy Management use case

- labs/university-course-fabric.md
- labs/university-course.md
Build a university course on Hyperledger technologies, with emphasis on Hyperledger Fabric.
> Enterprise Blockchain Technologies - A University Course on Hyperledger Technologies

- labs/xcsi.md
Signed-off-by: Vipin Bharathan <vipinsun@gmail.com>
Cross chain settlement instruction
> Lab proposal Cross chain settlement instruction

- labs/pubsub-interop.md
A blockchain interoperability solution for permissioned blockchain networks based on a publish/subscribe pattern.
Signed-off-by: Sara Ghaemi <ghaemi.sr@gmail.com>
Co-Authored-By: Rafael Belchior <rafael.belchior@tecnico.ulisboa.pt>
> Proposal for Publish/Subscribe based Blockchain Interoperability

- besu-operator.md
Kubernetes operator to provide an easier way of packaging, deploying, and managing Hyperledger Besu network.
Part of Hyperledger mentorship program : [Wiki Page](https://wiki.hyperledger.org/pages/viewpage.action?pageId=31195317)
Signed-off-by: Sumaid Syed <sumaidsyed@gmail.com>
> Besu Operator

- labs/avalon-sdk-py.md
avalon-sdk-py is the Python SDK for Hyperleder Avalon.
Signed-off-by: Divya Taori <divya.taori@wipro.com>
> avalon-sdk-py

- labs/minifabric.md
Signed-off-by: Tong Li <litong01@us.ibm.com>
> Minifabric Lab Proposal

- labs/blockchain-carbon-accounting.md
CO2 emissions accounting calculations using Hyperledger Fabric
Thanks @C0rWin for looking through it.
> blockchain-carbon-accounting

- labs/StarterKit.md
Lab  proposal for HL Starterkit
Signed-off-by: Ravi Vasagam <ravinayag@gmail.com>
> lab proposal for HL-StarterKit

- labs/fabric-opssc.md
Operations Smart Contract (OpsSC) is a smart contract-based system operation tool for Hyperledger Fabric-based systems,
which aims to enable efficient decentralized system operations across multiple organizations.
Signed-off-by: Tatsuya Sato <Tatsuya.Sato@hal.hitachi.com>
> Operations Smart Contract for Hyperledger Fabric

- labs/cordentity.md
The covid cause to a high demand on digital identity technology. The Cordentity implements an efficient way to connect Indy and Corda so it makes possible to build sophisticated use cases where a verifier accepts credentials directly to a private decentralized network. The project was archived in 2019 due to low support, but in the mid/end of 2020 there is a number of external requests to unfreeze the project.
Signed-off-by: Alexander Kopnin <alkopnin@gmail.com>
Signed-off-by: Ry Jones <ry@linux.com>
> Unarchive the cordentity project

- labs/weaver-dlt-interoperability.md
Signed-off-by: VRamakrishna <vramakr2@in.ibm.com>
_Short Description_: A platform, a protocol suite, and a set of tools, to enable interoperation for data sharing and asset movements between independent networks built on heterogeneous blockchain, or more generally, distributed ledger, technologies, in a manner that preserves the core blockchain tenets of decentralization and security.
> weaver-dlt-interoperability

- labs/mir-bft.md
Signed-off-by: Marko Vukolic <mvu@zurich.ibm.com>
> proposal for Mir-BFT scalable BFT protocol as a new Hyperledger Lab

- labs/fabric-machine.md
FPGA-based hardware acceleration for Hyperledger Fabric.
Signed-off-by: Haris Javaid <harisj@xilinx.com>
> New Labs Proposal: Fabric Machine

- labs/yui.md
Sorry, our proposal text doesn't include a header.
This PR fixes it.
> YUI: Add a header to the proposal

- labs/hlf-operator.md
Manage Hyperledger Fabric components at scale with a Kubernetes Operator.
I think there's a gap to deploy a Hyperledger Fabric network in Kubernetes, this project automates to automate the deployment.
The work will be focused on automating the creation of peers, orderers and CAs.
I have some ideas I would like to share such as developing a User Interface, and I think this could be integrated natively with the [fabric-operations-console](https://github.com/hyperledger-labs/fabric-operations-console) which was recently released.
> Hyperledger Fabric Operator for Kubernetes

- labs/nifty.md
nifty will be a low-code, metaprogrammable, standards sensitive and highly secure implementation to issue and trade NFTs, in a protocol agnostic way. 
nifty code will address market place utilities for issuance and trading of NFTs. 
Signed-off-by: Vipin Bharathan <vipinsun@gmail.com>
> create a new lab: nifty

- labs/hlf-connector.md
Signed-off-by: Anand Banik <anand.banik@walmart.com>
Integrate with Hyperledger Fabric using REST and Kafka and, Block and Chaincode Event emitter.
> hlf-connector

- labs/aries-fabric.md
This is a PR for creating a lab project for Aries wrapper to Fabric Network
Self - Sovereign Identity application is an application by which you are able to keep your identity secured and at the same time also prove your identity to the verifier without revealing them. These applications are built using Hyperledger Aries, which depends on Indy as a Distributed Ledger and Ursa as a cryptography library. Currently, the most used Blockchain platform is Hyperledger Fabric. And the businesses that are building solutions using Fabric want to have some sort of identity verification to be done in their platform. This is the reason, why this project has come into existence. Once done it would enable Aries to interact with Fabric as a ledger, which would then enable SSI applications to be built on …
> Aries Wrapper for Fabric

- README.md
This makes explicit the steps to follow after a lab is dormant.
> Add explicit lifecycle to labs

- labs/nft-community-footprint.md
Mint tokens for contributors' foot prints in fabric community.
Signed-off-by: Wan Yong <wan_yong@msn.com>
> NFT Community Footprint

- labs/karma-charity-platform.md
Signed-off-by: Alexander Zemtsov <a.zemtsov@gmail.com>
> Blockchain-based charity foundation platform

- labs/fabric-operator.md
This PR is a lab proposal for **fabric-operator**, a cloud-native operator for building, administering, and maintaining Hyperledger Fabric networks on Kubernetes.
Signed-off-by: Josh Kneubuhl <jkneubuh@us.ibm.com>
> Fabric Operator Labs Proposal

- proposal.md
> Add lightly edited Proposal

- stewards.md
* Emeritus Stewards
* How to become a steward
Signed-off-by: Tracy Kuhrt <tracy.a.kuhrt@accenture.com>
> Add Steward Info

- stewards.md
Signed-off-by: Tracy Kuhrt <tracy.a.kuhrt@accenture.com>
> Add newline

- stewards.md
Volunteering to be Lab Steward
Name: Anand Banik
TSC Sponsor - @arsulegai.
Signed-off-by: Anand Banik <anand.banik@walmart.com>
> Add Anand Banik as a Lab Steward

- labs/fabric-weft.md
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
> Weft Proposal

- mosaique-decentralized-workflows.md
Mosaique provides an approach to build decentralized workflows for permissioned blockchain applications. Mosaique has built-in governance workflows using mosaique itself. The systems uses state machines for the workflow logic and json templates to make those state machines data-driven. The goal is to allow non-programmers develop and analyze their decentralized workflows and to deploy without having to change smart contract code.
> Mosaique Decentralized Workflows

- labs/fabric-channeled-add-ons-gen.md
Signed-off-by: Nikos Kapsoulis <nkapsoulis@gmail.com>
> Fabric Channeled Add-ons Gen Proposal

- labs/fabric-ansible-collection.md
Signed-off-by: Matthew B White <whitemat@uk.ibm.com>
> Ansible collection proposal

- stewards.md
Pending on TOC approval. @tkuhrt
> Propose Nidhi as Steward

- labs/aries-sdk-mendix.md
After feedback from the OWF technical advisory committee, it was advised that "wrapper" implementations to Aries should probably be maintained out of Hyperledger given the extensive Aries resources currently maintained out of this community.
> aries-sdk-mendix lab proposal submission

- labs/open-enterprise-agent.md
The Open Enterprise Agent is a software agent for building decentralised identity applications and services in line with W3C standards and Hyperledger Aries RFCs. Aiming to be blockchain agnostic and interoperable across two key technology ecosystems in SSI, it provides a scalable, robust, performant and user-friendly platform for building solutions and products based on it. Its REST API enables easy integration with any programming language, on top of a core built in Scala, a language well suited for building fault-tolerant, highly concurrent systems.
> Open Enterprise Agent

- labs/blockchain-explorer.md
Blockchain Explorer is a simple, powerful, easy-to-use, well-maintained, open-source utility to browse activity 
on the underlying blockchain network.
> Blockchain Explorer

- labs/CC-Tools.md
The CC-Tools package provides a relational-like framework for programming Hyperledger Fabric chaincodes.
> CC-Tools lab

- labs/agora.md
Agora serves as a specialized lab, purposefully designed to function as a secure and collaborative environment for the 
implementation and advancement of cryptography libraries and software. 
Much like the ancient Greek agora served as a gathering place for assemblies and open markets, this lab is tailored 
to incorporate cryptography protocols that facilitate experimentation, development, and eventual application integration. 
While its primary focus is on production-ready usage, Agora also accommodates research code contributions.
Numerous libraries featured in Agora are already in active use within production systems. 
By incorporating them into the lab, we ensure greater continuity and reliability, 
mitigating the risk of code vanishing due to a single developer's involvement and …
> Agora, a Hyperledger Lab

- labs/fabric-java-token-sdk.md
This project has the objective to create and provide a java interface to the project [Fabric Token SDK](https://github.com/hyperledger-labs/fabric-token-sdk)
> Fabric java token sdk

- labs/automated_gateways.md
Automated Gateways is a secure solution which can make Contract-Call interoperatibility happen between Hyperledger Fabrics with minimal efforts.
> Automated-Gateways 

- labs/archived/aries-sdk-mendix.md
> Archive aries-sdk-mendix

- labs/learning-tokens.md
Updated & added Learning proposal-template with following section 
- initial committers
- pre-existing repository
- contact
- web portal
- publication section
> Learning Token

- labs/archived/open-enterprise-agent.md
> Open Enterprise Agent became Identus

- labs/jsonld-vc-bbs-go.md
Golang implementation of W3C JSON-LD BBS credentials
> JsonLD VC BBS Go

- labs/lfdt/paladin.md
> Update Paladin description

- labs/lfdt/chainlaunch.md
Donate the project ChainLaunch to LFDT Labs.
> ChainLaunch

- labs/lfdt/cbweb3.md
CBWeb3 aims to enable a regional test network for tokenized security markets to enable cross-region interoperability among Central Banks, financial institutions and people in several countries of the Latin American and Caribbean region. The prototype innovation consists of designing and deploying a complete functional architecture to model and experiment with settlement. A Testnet is a testing environment that allows central banks to experiment with issues such as token emissions, cross-border payments, real-time settlement, among others. The value of this Testnet lies in enabling central banks to conduct these experiments through a unique interoperable protocol, ensuring compatibility for experimentation among beneficiary countries.
> Proposal to add CBWeb3 as a new lab

- labs/lfdt/fabric-chaincode-builder.md
- proposal-template.md
> fabric-chaincode-builder lab added

- labs/lfdt/aries-labs.md
> Aries labs

- labs/lfdt/zk-learning-group.md
> zk learning group lab added

- README.md
- index.md
> Remove some Hyperledger verbiage

- labs/lfdt/cello.md
> Move Hyperledger Cello to a lab

- labs/hyperledger/verazt.md
- labs/lfdt/verazt.md
Verazt is a smart contract security toolkit that provides a set of tools performing static analysis, formal verification, and fuzz-testing to find security vulnerabilities in smart contracts.
> Verazt Labs
